name: publish.yml
on: [ release ]

jobs:
  publish:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version-file: pyproject.toml
      - uses: astral-sh/setup-uv@v6
        with:
          enable-cache: 'auto'
      - name: Set version
        run: uv version $(git describe --tags)
      - name: run build
        run: uv build
      - name: Publish to PyPI
        run: uv publish

